CREATE DATABASE IF NOT EXISTS quanlykhachsan;
USE quanlykhachsan;

CREATE TABLE invoice (
    id VARCHAR(255) PRIMARY KEY,
    invoice_type VARCHAR(10) NOT NULL,
    room_id VARCHAR(255) NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    billed_date DATE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users(
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE invoice_type (
    code VARCHAR(10) PRIMARY KEY,
    name_type VARCHAR(255) NOT NULL
);

CREATE TABLE invoice_hl (
    invoice_id VARCHAR(255) PRIMARY KEY,
    rental_hours BIGINT NOT NULL,
);

CREATE TABLE invoice_dl (
    invoice_id VARCHAR(255) PRIMARY KEY,
    rental_days BIGINT NOT NULL,
);